collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.18363129626959562
color:
  saturation: 0.4694444693159312
  brandStrength: 0.9755451350938529
  rhythmicContrast: 0.9536227993667126
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.0396144799888134
layout_spectrum: 0.8360042043495923
name: FORGE3D
navigation:
  - id: 'https://www.etsy.com/uk/shop/FORGE3Duk?ref=hdr_shop_menu'
    url: 'https://www.etsy.com/uk/shop/FORGE3Duk?ref=hdr_shop_menu'
    name: Etsy store
    type: external
