typography_spectrum: 0.4756209719926119
content_rating:
  adult: false
color:
  saturation: 0.17764981859363616
  brandStrength: 0.38939997903071344
  rhythmicContrast: 0.12436232715845108
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  lightness: 0.8152144192717969
layout_spectrum: 0.08981688064523041
logo: null
name: FORGE 3D
navigation: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/166c019e-3e78-4f48-9cf3-8968cd502a18.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: FORGE 3D
description: 3D printing
