collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#303030'
    - '#000000'
    - '#6B6968'
    - '#9FA09B'
    - '#CFCFC3'
  rhythmicContrast: 0
typography_spectrum: 0.5480607
layout_spectrum: 0.6033835
name: FORGE3D
