collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5517529402859509
  brandStrength: 0.5796850363258272
  lightness: 0.9003097601234913
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  rhythmicContrast: 0.165939224883914
typography_spectrum: 0.8895440921187401
layout_spectrum: 0.5240703683812171
name: FORGE3D
